<?php
function groceries_menu() {
  $items = array();
  $items['groceries'] = array(
    'title' => 'Grocerie List',
    'page callback' => 'groceries',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function groceries() {
  $groceries['eggs'] = array(
    'price' => '1.99',
    'quantity' => 's',
  );

  $list = '';
  foreach ($groceries as $item => $value) {
    $list .= "<p> $item: </p>";
    foreach ($groceries[$item] as $info) {
      $list .= "<p> $info </p>";
    }
  }
  return $list;
}
